---

  - name: install haproxy
    apt:
      name: haproxy
      update_cache: true
      state: latest

  - name: replace default config
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      owner: vagrant
      group: vagrant
      mode: 0644
    notify: reload haproxy
