---

# install vagrant with libvirt for fedora
  - name: install dnf-plugins-core
    dnf:
      name: dnf-plugins-core
      update_cache: true
      state: present

  - name: add repository vagrant
    shell: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    args:
      creates: /etc/yum.repos.d/hashicorp.repo

  - name: install vagrant
    dnf:
      name: vagrant
      update_cache: true
      state: present

  - name: vagrant plugin list
    become: false
    shell: vagrant plugin list
    register: vagrant_plugin_list

  - name: vagrant plugin install
    become: false
    shell: vagrant plugin install vagrant-libvirt
    when: not 'vagrant-libvirt' in vagrant_plugin_list.stdout

  - name: vagrant up
    become: false
    shell:
      cmd: vagrant up
      chdir: "{{ dir_vagrantfile }}"