---

- hosts: localhost
  become: true
  gather_facts: false
  vars_files:
    - vars/wordpress_vault.yml
  roles:
    - { role: vagrant, tags: [vagrant] }

- hosts: wordpress
  become: true
  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml
  roles:
    - { role: nginx, tags: [nginx] }
    - { role: php, tags: [php] }
    - { role: wordpress, tags: [wordpress] }

  post_tasks:
  - name: restart php
    systemd:
      name: php7.4-fpm
      state: restarted
      enabled: true

  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: true

- hosts: database
  become: true
  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml
  roles:
    - { role: mysql, tags: [mysql] }

- hosts: haproxy
  become: true
  roles:
    - { role: haproxy, tags: [haproxy] }